xcodeproj 'DTCollectionViewManagerExample.xcodeproj'
inhibit_all_warnings!
platform :ios, 6.0

pod 'DTModelStorage', '0.8.0'
pod 'PlaceKit', '~> 1.0.0'

target :Tests do
  pod 'Cedar'
  pod 'AutoDescribe'
  pod 'OCMock', '~> 2.2.1'
end