require 'cocoapods'
 
scheme_name = "XCTests"
 
def run(command, min_exit_status = 0)
  puts "Executing: `#{command}`"
  system(command)
  return $?.exitstatus
end
 
desc "Cleaning environment"
task :clean do
  run("rm -rf Build && rm -rf DerivedData")
end
 
desc "Run #{scheme_name} tests"
task :run_tests do
  $tests_success = run("set -o pipefail && xcodebuild -scheme \"#{scheme_name}\" -destination 'name=iPad Air' clean test")
end
 
desc "Test and compile #{scheme_name}"
task :ci =>  ['clean','run_tests'] do 
  puts "\033[0;31m! #{scheme_name} unit tests failed" unless $tests_success == 0
  if ($tests_success == 0)
    puts "\033[0;32m** All is good!"
  else
    exit(-1)
  end
end
 
task default: 'ci'